version: '3.7'

services:
  react:
    build:
      context: ../app/frontend/react
      dockerfile: Dockerfile.development
    command: 'yarn start'
    volumes:
      - ../app/frontend/react:/usr/src/app/toHost

  django:
    build: ../app/backend/django
    command: 'gunicorn podium.wsgi:application --bind 0.0.0.0:8000'
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./data/env/development.env
    depends_on:
      - postgres

  node:
    build: ../app/backend/websockets
    command: node server.js

  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./data/env/development.env

  nginx:
    image: nginx:1.15-alpine
    command: '/bin/sh -c "while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g ''daemon off;''"'
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - ./data/nginx/development:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - react
      - django
      - node

volumes:
  static_volume:
  media_volume:
  postgres_volume:
